export const sittingPlanArray = [
  {
    firstName: "Marta",
    lastName: "Brzózka",
    tableNr: 1,
    chairNr: 1,
  },
  {
    firstName: "Błażej",
    lastName: "Brzózka",
    tableNr: 1,
    chairNr: 2,
  },
  {
    firstName: "Michał",
    lastName: "Krasuski",
    tableNr: 1,
    chairNr: 3,
  },
  {
    firstName: "Krystyna",
    lastName: "Janik",
    tableNr: 1,
    chairNr: 4,
  },
  {
    firstName: "Małgorzata",
    lastName: "Wysocka",
    tableNr: 1,
    chairNr: 5,
  },
  {
    firstName: "Małgorzata",
    lastName: "Wysocka+1",
    tableNr: 1,
    chairNr: 6,
  },
  {
    firstName: "Krystyna",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 1,
  },
  {
    firstName: "Antoni",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 2,
  },
  {
    firstName: "Alicja",
    lastName: "Nabiałek",
    tableNr: 2,
    chairNr: 3,
  },
  {
    firstName: "Bożena",
    lastName: "Janik",
    tableNr: 2,
    chairNr: 4,
  },
  {
    firstName: "Mikołaj",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 5,
  },
  {
    firstName: "Weronika",
    lastName: "Chrząstek",
    tableNr: 2,
    chairNr: 6,
  },
  {
    firstName: "Patryk",
    lastName: "Urbaniak (boczek)",
    tableNr: 2,
    chairNr: 7,
  },
  {
    firstName: "Sandra",
    lastName: "Raźna",
    tableNr: 2,
    chairNr: 8,
  },
  {
    firstName: "Bartek",
    lastName: "Skrabka",
    tableNr: 2,
    chairNr: 9,
  },
  {
    firstName: "Bartek",
    lastName: "Skrabka +1",
    tableNr: 2,
    chairNr: 10,
  },
  {
    firstName: "Mariusz",
    lastName: "Chrząstek",
    tableNr: 2,
    chairNr: 11,
  },
  {
    firstName: "Ewa",
    lastName: "Chrząstek",
    tableNr: 2,
    chairNr: 12,
  },
  {
    firstName: "Andrzej",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 13,
  },
  {
    firstName: "Beata",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 14,
  },
  {
    firstName: "Mateusz",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 15,
  },
  {
    firstName: "Elżbeta",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 16,
  },
  {
    firstName: "Adam",
    lastName: "Nowak",
    tableNr: 2,
    chairNr: 17,
  },
  {
    firstName: "Adam",
    lastName: "Nowak + 1",
    tableNr: 2,
    chairNr: 18,
  },
  {
    firstName: "Kamil",
    lastName: "Bodzak",
    tableNr: 2,
    chairNr: 19,
  },
  {
    firstName: "Kamil",
    lastName: "Bodzak + 1",
    tableNr: 2,
    chairNr: 20,
  },
  {
    firstName: "Maria",
    lastName: "Wójcik",
    tableNr: 3,
    chairNr: 1,
  },
  {
    firstName: "Maksymilian",
    lastName: "Wójcik",
    tableNr: 3,
    chairNr: 2,
  },
  {
    firstName: "Dominika",
    lastName: "Janik",
    tableNr: 3,
    chairNr: 3,
  },
  {
    firstName: "Szymon",
    lastName: "Janik",
    tableNr: 3,
    chairNr: 4,
  },
  {
    firstName: "Stanisław",
    lastName: "Bernat",
    tableNr: 3,
    chairNr: 5,
  },
  {
    firstName: "Adam",
    lastName: "Sadowski",
    tableNr: 3,
    chairNr: 6,
  },
  {
    firstName: "Magdalena",
    lastName: "Nawrocka",
    tableNr: 3,
    chairNr: 7,
  },
  {
    firstName: "Dorota",
    lastName: "Dobrzyńska",
    tableNr: 3,
    chairNr: 8,
  },
  {
    firstName: "Paweł",
    lastName: "Dobrzyński",
    tableNr: 3,
    chairNr: 9,
  },
  {
    firstName: "Sonia",
    lastName: "Wałachowska",
    tableNr: 3,
    chairNr: 10,
  },
  {
    firstName: "Karol",
    lastName: "Wałachowski",
    tableNr: 3,
    chairNr: 11,
  },
  {
    firstName: "Marta",
    lastName: "Chocian",
    tableNr: 3,
    chairNr: 12,
  },
  {
    firstName: "Marta",
    lastName: "Chocian + 1",
    tableNr: 3,
    chairNr: 13,
  },
  {
    firstName: "Katarzyna",
    lastName: "Rodkiewicz",
    tableNr: 3,
    chairNr: 14,
  },
  {
    firstName: "Marek",
    lastName: "Rodkiewicz",
    tableNr: 3,
    chairNr: 15,
  },
  {
    firstName: "Żaneta",
    lastName: "Szulhan",
    tableNr: 3,
    chairNr: 16,
  },
  {
    firstName: "Krzysztof",
    lastName: "Ziembicki",
    tableNr: 3,
    chairNr: 17,
  },
  {
    firstName: "Iwona",
    lastName: "Miller",
    tableNr: 3,
    chairNr: 18,
  },
  {
    firstName: "Carlos",
    lastName: "Bahri",
    tableNr: 3,
    chairNr: 19,
  },
  {
    firstName: "Maryla",
    lastName: "Sokołowska",
    tableNr: 4,
    chairNr: 1,
  },
  {
    firstName: "Krzystof",
    lastName: "Sokołowki",
    tableNr: 4,
    chairNr: 2,
  },
  {
    firstName: "Magdalena",
    lastName: "Krasuska",
    tableNr: 4,
    chairNr: 3,
  },
  {
    firstName: "Tomasz",
    lastName: "Krasuski",
    tableNr: 4,
    chairNr: 4,
  },
  {
    firstName: "Ewa",
    lastName: "Krasuska",
    tableNr: 4,
    chairNr: 5,
  },
  {
    firstName: "Krystyna",
    lastName: "Szymańska",
    tableNr: 4,
    chairNr: 6,
  },
  {
    firstName: "Sławomir",
    lastName: "Sierputowski",
    tableNr: 4,
    chairNr: 7,
  },
  {
    firstName: "Iwona",
    lastName: "Sierputowska",
    tableNr: 4,
    chairNr: 8,
  },
  {
    firstName: "Leszek",
    lastName: "Sikora",
    tableNr: 4,
    chairNr: 9,
  },
  {
    firstName: "Barbara",
    lastName: "Sikora",
    tableNr: 4,
    chairNr: 10,
  },
  {
    firstName: "Stanisław",
    lastName: "Krasuski",
    tableNr: 4,
    chairNr: 11,
  },
  {
    firstName: "Kazimiera",
    lastName: "Jankowska",
    tableNr: 4,
    chairNr: 12,
  },
  {
    firstName: "Łukasz",
    lastName: "Sokołowski",
    tableNr: 4,
    chairNr: 13,
  },
  {
    firstName: "Ewa",
    lastName: "Zarębska",
    tableNr: 4,
    chairNr: 14,
  },
  {
    firstName: "Jarosław",
    lastName: "Sokołowski",
    tableNr: 4,
    chairNr: 15,
  },
  {
    firstName: "Sławek",
    lastName: "Panek",
    tableNr: 4,
    chairNr: 16,
  },
  {
    firstName: "Łukasz",
    lastName: "Sierputowski",
    tableNr: 4,
    chairNr: 17,
  },
  {
    firstName: "Agnieszka",
    lastName: "Niedośmiałek",
    tableNr: 4,
    chairNr: 18,
  },
  {
    firstName: "Emilia",
    lastName: "Sierputowska",
    tableNr: 4,
    chairNr: 19,
  },
  {
    firstName: "Maja",
    lastName: "Szymańska",
    tableNr: 4,
    chairNr: 20,
  },
  {
    firstName: "Maja",
    lastName: "Szymańska+1",
    tableNr: 4,
    chairNr: 21,
  },
  {
    firstName: "Mikołaj",
    lastName: "Szymański",
    tableNr: 4,
    chairNr: 22,
  },
  {
    firstName: "Dariusz",
    lastName: "Szymański",
    tableNr: 4,
    chairNr: 23,
  },
  {
    firstName: "Dariusz",
    lastName: "Szymański+1",
    tableNr: 4,
    chairNr: 24,
  },
];

export default sittingPlanArray;
