export const sittingPlanArray = [
  {
    firstName: "Marta",
    lastName: "Brzózka",
    tableNr: 1,
    chairNr: 1,
  },
  {
    firstName: "Błażej",
    lastName: "Brzózka",
    tableNr: 1,
    chairNr: 2,
  },
  {
    firstName: "Michał",
    lastName: "Krasuski",
    tableNr: 1,
    chairNr: 3,
  },
  {
    firstName: "Krystyna",
    lastName: "Janik",
    tableNr: 1,
    chairNr: 4,
  },
  {
    firstName: "Małgorzata",
    lastName: "Wysocka",
    tableNr: 1,
    chairNr: 5,
  },
  {
    firstName: "Małgorzata",
    lastName: "Wysocka+1",
    tableNr: 1,
    chairNr: 6,
  },
  {
    firstName: "Sonia",
    lastName: "Wałachowska",
    tableNr: 2,
    chairNr: 1,
  },
  {
    firstName: "Karol",
    lastName: "Wałachowski",
    tableNr: 2,
    chairNr: 2,
  },
  {
    firstName: "Dominika",
    lastName: "Janik",
    tableNr: 2,
    chairNr: 3,
  },
  {
    firstName: "Szymon",
    lastName: "Janik",
    tableNr: 2,
    chairNr: 4,
  },
  {
    firstName: "Maria",
    lastName: "Wójcik",
    tableNr: 2,
    chairNr: 5,
  },
  {
    firstName: "Maksymilian",
    lastName: "Wójcik",
    tableNr: 2,
    chairNr: 6,
  },
  {
    firstName: "Monika",
    lastName: "Zakowicz",
    tableNr: 2,
    chairNr: 7,
  },
  {
    firstName: "Maxime",
    lastName: "Guidon",
    tableNr: 2,
    chairNr: 8,
  },
  {
    firstName: "Maryla",
    lastName: "Sokołowska",
    tableNr: 3,
    chairNr: 1,
  },
  {
    firstName: "Krzystof",
    lastName: "Sokołowki",
    tableNr: 3,
    chairNr: 2,
  },
  {
    firstName: "Ewa",
    lastName: "Krasuska",
    tableNr: 3,
    chairNr: 3,
  },
  {
    firstName: "Magdalena",
    lastName: "Krasuska",
    tableNr: 3,
    chairNr: 4,
  },
  {
    firstName: "Tomasz",
    lastName: "Krasuski",
    tableNr: 3,
    chairNr: 5,
  },
  {
    firstName: "Łukasz",
    lastName: "Sokołowski",
    tableNr: 3,
    chairNr: 6,
  },
  {
    firstName: "Łukasz",
    lastName: "Sokołowski +1",
    tableNr: 3,
    chairNr: 7,
  },
  {
    firstName: "Jarosław",
    lastName: "Sokołowski",
    tableNr: 3,
    chairNr: 8,
  },
  {
    firstName: "Ewa",
    lastName: "Zarębska",
    tableNr: 3,
    chairNr: 9,
  },
  {
    firstName: "Sławek",
    lastName: "Panek",
    tableNr: 3,
    chairNr: 10,
  },
  {
    firstName: "Krystyna",
    lastName: "Nowak",
    tableNr: 4,
    chairNr: 1,
  },
  {
    firstName: "Antoni",
    lastName: "Nowak",
    tableNr: 4,
    chairNr: 2,
  },
  {
    firstName: "Beata",
    lastName: "Nowak",
    tableNr: 4,
    chairNr: 3,
  },
  {
    firstName: "Andrzej",
    lastName: "Nowak",
    tableNr: 4,
    chairNr: 4,
  },
  {
    firstName: "Alicja",
    lastName: "Nabiałek",
    tableNr: 4,
    chairNr: 5,
  },
  {
    firstName: "Bożena",
    lastName: "Janik",
    tableNr: 4,
    chairNr: 6,
  },
  {
    firstName: "Ewa",
    lastName: "Chrząstek",
    tableNr: 4,
    chairNr: 7,
  },
  {
    firstName: "Mariusz",
    lastName: "Chrząstek",
    tableNr: 4,
    chairNr: 8,
  },
  {
    firstName: "Elżbeta",
    lastName: "Nowak",
    tableNr: 6,
    chairNr: 1,
  },
  {
    firstName: "Mateusz",
    lastName: "Nowak",
    tableNr: 6,
    chairNr: 2,
  },
  {
    firstName: "Mikołaj",
    lastName: "Nowak",
    tableNr: 6,
    chairNr: 3,
  },
  {
    firstName: "Emilia",
    lastName: "Sierputowska",
    tableNr: 6,
    chairNr: 4,
  },
  {
    firstName: "Łukasz",
    lastName: "Sierputowski",
    tableNr: 6,
    chairNr: 5,
  },
  {
    firstName: "Adam",
    lastName: "Nowak",
    tableNr: 6,
    chairNr: 6,
  },
  {
    firstName: "Adam",
    lastName: "Nowak + 1",
    tableNr: 6,
    chairNr: 7,
  },
  {
    firstName: "Agnieszka",
    lastName: "Niedośmiałek",
    tableNr: 6,
    chairNr: 8,
  },
  {
    firstName: "Mikołaj",
    lastName: "Szymański",
    tableNr: 6,
    chairNr: 9,
  },
  {
    firstName: "Mikołaj",
    lastName: "Szymański+1",
    tableNr: 6,
    chairNr: 10,
  },
  {
    firstName: "Stanisław",
    lastName: "Krasuski",
    tableNr: 7,
    chairNr: 1,
  },
  {
    firstName: "Kazimiera",
    lastName: "Jankowska",
    tableNr: 7,
    chairNr: 2,
  },
  {
    firstName: "Iwona",
    lastName: "Sierputowska",
    tableNr: 7,
    chairNr: 3,
  },
  {
    firstName: "Sławomir",
    lastName: "Sierputowski",
    tableNr: 7,
    chairNr: 4,
  },
  {
    firstName: "Dariusz",
    lastName: "Szymański",
    tableNr: 7,
    chairNr: 5,
  },
  {
    firstName: "Dariusz",
    lastName: "Szymański+1",
    tableNr: 7,
    chairNr: 6,
  },
  {
    firstName: "Krystyna",
    lastName: "Szymańska",
    tableNr: 7,
    chairNr: 7,
  },
  {
    firstName: "Barbara",
    lastName: "Sikora",
    tableNr: 7,
    chairNr: 8,
  },
  {
    firstName: "Leszek",
    lastName: "Sikora",
    tableNr: 7,
    chairNr: 9,
  },
  {
    firstName: "Andrea",
    lastName: "Rijnohosa",
    tableNr: 8,
    chairNr: 1,
  },
  {
    firstName: "Andrea",
    lastName: "Rijnohosa +1",
    tableNr: 8,
    chairNr: 2,
  },
  {
    firstName: "Carlos",
    lastName: "Bahri",
    tableNr: 8,
    chairNr: 3,
  },
  {
    firstName: "Iwona",
    lastName: "Miller",
    tableNr: 8,
    chairNr: 4,
  },
  {
    firstName: "Paweł",
    lastName: "Dobrzyński",
    tableNr: 8,
    chairNr: 5,
  },
  {
    firstName: "Krzysztof",
    lastName: "Ziembicki",
    tableNr: 8,
    chairNr: 6,
  },
  {
    firstName: "Żaneta",
    lastName: "Szulhan",
    tableNr: 8,
    chairNr: 7,
  },
  {
    firstName: "Anna",
    lastName: "Rusiniak",
    tableNr: 8,
    chairNr: 8,
  },
  {
    firstName: "Piotr",
    lastName: "Rusinak",
    tableNr: 8,
    chairNr: 9,
  },
  {
    firstName: "Dorota",
    lastName: "Dobrzyńska",
    tableNr: 8,
    chairNr: 10,
  },
  {
    firstName: "Marta",
    lastName: "Chocian",
    tableNr: 9,
    chairNr: 1,
  },
  {
    firstName: "Marta",
    lastName: "Chocian + 1",
    tableNr: 9,
    chairNr: 2,
  },
  {
    firstName: "Magdalena",
    lastName: "Nawrocka",
    tableNr: 9,
    chairNr: 3,
  },
  {
    firstName: "Magdalena",
    lastName: "Nawrocka + 1",
    tableNr: 9,
    chairNr: 4,
  },
  {
    firstName: "Jadwiga",
    lastName: "Banach",
    tableNr: 9,
    chairNr: 5,
  },
  {
    firstName: "Piotr",
    lastName: "Taszkun",
    tableNr: 9,
    chairNr: 6,
  },
  {
    firstName: "Katarzyna",
    lastName: "Rodkiewicz",
    tableNr: 9,
    chairNr: 7,
  },
  {
    firstName: "Marek",
    lastName: "Rodkiewicz",
    tableNr: 9,
    chairNr: 8,
  },
];

export default sittingPlanArray;
