export const sittingPlanArray = [
  {
    firstName:'Marta',
    lastName:'Brzózka',
    tableNr: 1,
    chairNr: 1,
},
{
    firstName:'Błażej',
    lastName:'Brzózka',
    tableNr: 1,
    chairNr: 2,
},
{
    firstName:'Michał',
    lastName:'Krasuski',
    tableNr: 1,
    chairNr: 3,
},
{
    firstName:'Krystyna',
    lastName:'Janik',
    tableNr: 1,
    chairNr: 4,
},
{
    firstName:'Małgorzata',
    lastName:'Wysocka',
    tableNr: 1,
    chairNr: 5,
},
{
    firstName:'Antoni',
    lastName:'Nowak',
    tableNr: 2,
    chairNr: 1,
},
{
    firstName:'Krystyna',
    lastName:'Nowak',
    tableNr: 2,
    chairNr: 2,
},
{
    firstName:'Mariusz',
    lastName:'Chrząstek',
    tableNr: 2,
    chairNr: 3,
},
{
    firstName:'Ewa',
    lastName:'Chrząstek',
    tableNr: 2,
    chairNr: 4,
},
{
    firstName:'Sławek',
    lastName:'Panek',
    tableNr: 2,
    chairNr: 5,
},
{
  firstName:'Tomasz',
  lastName:'Krasuski',
  tableNr: 2,
  chairNr: 6,
},
{
    firstName:'Magdalena',
    lastName:'Krasuska',
    tableNr: 2,
    chairNr: 7,
},
{
    firstName:'Iwona',
    lastName:'Sierputowska',
    tableNr: 2,
    chairNr: 8,
},
{
    firstName:'Sławomir',
    lastName:'Sierputowski',
    tableNr: 2,
    chairNr: 9,
},
{
    firstName:'Beata',
    lastName:'Nowak',
    tableNr: 2,
    chairNr: 10,
},
{
    firstName:'Andrzej',
    lastName:'Nowak',
    tableNr: 2,
    chairNr: 11,
},
{
    firstName:'Alicja',
    lastName:'Nabiałek',
    tableNr: 2,
    chairNr: 12,
},
{
    firstName:'Bożena',
    lastName:'Janik',
    tableNr: 2,
    chairNr: 13,
},
{
    firstName:'Krzystof',
    lastName:'Sokołowki',
    tableNr: 2,
    chairNr: 14,
},
{
    firstName:'Maryla',
    lastName:'Sokołowska',
    tableNr: 2,
    chairNr: 15,
},
{
    firstName:'Ewa',
    lastName:'Krasuska',
    tableNr: 2,
    chairNr: 16,
},
{
    firstName:'Krystyna',
    lastName:'Szymańska',
    tableNr: 2,
    chairNr: 17,
},
{
    firstName:'Stanisław',
    lastName:'Krasuski',
    tableNr: 2,
    chairNr: 18,
},
{
    firstName:'Kazimiera',
    lastName:'Jankowska',
    tableNr: 2,
    chairNr: 19,
},
{
    firstName:'Kamil',
    lastName:'Bodzak',
    tableNr: 3,
    chairNr: 1,
},
{
    firstName:'Kamil',
    lastName:'Bodzak + 1',
    tableNr: 3,
    chairNr: 2,
},
{
    firstName:'Bartek',
    lastName:'Skrabka',
    tableNr: 3,
    chairNr: 3,
},
{
    firstName:'Aleksandra',
    lastName:'Mikołajek',
    tableNr: 3,
    chairNr: 4,
},
{
    firstName:'Łukasz',
    lastName:'Sokołowski',
    tableNr: 3,
    chairNr: 5,
},
{
    firstName:'Ewa',
    lastName:'Zarębska',
    tableNr: 3,
    chairNr: 6,
},
{
    firstName:'Jarosław',
    lastName:'Sokołowski',
    tableNr: 3,
    chairNr: 7,
},
{
    firstName:'Bartek',
    lastName:'Łukasiewicz',
    tableNr: 3,
    chairNr: 8,
},
{
    firstName:'Maja',
    lastName:'Szymańska',
    tableNr: 3,
    chairNr: 9,
},
{
    firstName:'Kamil',
    lastName:'Czaplewski',
    tableNr: 3,
    chairNr: 10,
},
{
    firstName:'Aleksandra',
    lastName:'Oleksyn',
    tableNr: 3,
    chairNr: 11,
},
{
    firstName:'Patryk',
    lastName:'Urbaniak',
    tableNr: 3,
    chairNr: 12,
},
{
    firstName:'Sandra',
    lastName:'Raźna',
    tableNr: 3,
    chairNr: 13,
},
{
    firstName:'Mateusz',
    lastName:'Nowak',
    tableNr: 3,
    chairNr: 14,
},
{
    firstName:'Elżbeta',
    lastName:'Nowak',
    tableNr: 3,
    chairNr: 15,
},
{
    firstName:'Agnieszka',
    lastName:'Sierputowska',
    tableNr: 3,
    chairNr: 16,
},
{
    firstName:'Łukasz',
    lastName:'Sierputowski',
    tableNr: 3,
    chairNr: 17,
},
{
    firstName:'Emilia',
    lastName:'Sierputowska',
    tableNr: 3,
    chairNr: 18,
},
{
    firstName:'Maria',
    lastName:'Wójcik',
    tableNr: 4,
    chairNr: 1,
},
{
    firstName:'Maksymilian',
    lastName:'Wójcik',
    tableNr: 4,
    chairNr: 2,
},
{
    firstName:'Szymon',
    lastName:'Janik',
    tableNr: 4,
    chairNr: 3,
},
{
    firstName:'Dominika',
    lastName:'Janik',
    tableNr: 4,
    chairNr: 4,
},
{
    firstName:'Katarzyna',
    lastName:'Symonowicz',
    tableNr: 4,
    chairNr: 5,
},
{
    firstName:'Michał',
    lastName:'Rose',
    tableNr: 4,
    chairNr: 6,
},
{
    firstName:'Magdalena',
    lastName:'Nawrocka + 1',
    tableNr: 4,
    chairNr: 7,
},
{
    firstName:'Magdalena',
    lastName:'Nawrocka',
    tableNr: 4,
    chairNr: 8,
},
{
    firstName:'Katarzyna',
    lastName:'Rodkiewicz',
    tableNr: 4,
    chairNr: 9,
},
{
    firstName:'Marek',
    lastName:'Rodkiewicz',
    tableNr: 4,
    chairNr: 10,
},
{
    firstName:'Iwona',
    lastName:'Miler',
    tableNr: 4,
    chairNr: 11,
},
{
    firstName:'Carlos',
    lastName:'Bahri',
    tableNr: 4,
    chairNr: 12,
},
{
    firstName:'Sonia',
    lastName:'Wałachowska',
    tableNr: 4,
    chairNr: 13,
},
{
    firstName:'Karol',
    lastName:'Wałachowski',
    tableNr: 4,
    chairNr: 14,
},
{
    firstName:'Jakub',
    lastName:'Misiaszek',
    tableNr: 4,
    chairNr: 15,
},
{
    firstName:'Weronika',
    lastName:'Chrząstek',
    tableNr: 4,
    chairNr: 16,
},
{
    firstName:'Tatiana',
    lastName:'Chubarava',
    tableNr: 4,
    chairNr: 17,
},
{
    firstName:'Wiktor',
    lastName:'Lipiński',
    tableNr: 4,
    chairNr: 18,
},
{
    firstName:'Stanisław',
    lastName:'Bernat',
    tableNr: 4,
    chairNr: 19,
},
{
    firstName:'Adam',
    lastName:'Sadowski',
    tableNr: 4,
    chairNr: 20,
},
{
    firstName:'Marta',
    lastName:'Chocian',
    tableNr: 4,
    chairNr: 21,
},
{
    firstName:'Kamil',
    lastName:'Sabat',
    tableNr: 4,
    chairNr: 22,
},
{
    firstName:'Żaneta',
    lastName:'Szulhan',
    tableNr: 4,
    chairNr: 23,
},
{
    firstName:'Krzysztof',
    lastName:'Ziembicki',
    tableNr: 4,
    chairNr: 24,
},



];

export default sittingPlanArray;
